### PR TITLE
FC68125 - Audio Jack

### PR DESCRIPTION
**Pull request by dwaq**
Created model in OpenSCAD and imported 3D model into layout. I didn't add pins, but the outline of the model lines up. I also didn't add a "material" to the model so it's just plain white. Would you like for me to modify it in any way?
front_prototype

### CODE REVIEW

**Comment by CRImier** [comment]
Making it black would be nice. Of course, the goal is simply making a to-scale 3D model of ZeroPhone, so it's all good as long as the dimensions are right =)

**Comment by CRImier** [comment]
Hmm. 	ddb5789 - it uses absolute path from your computer. You could fix that, right? (I would myself, but I'm on the go right now).

**Comment by dwaq** [comment]
OK, let me try and make it black.

**Comment by dwaq** [comment]
Alright, I fixed the color and the path.
front_prototype

**Comment by CRImier** [comment]
Merged, thank you!

**Pull request merged**
