### PR TITLE
Add Raspberry Pi Zero model

### PR DESCRIPTION
**Pull request by dwaq**
See #12 

This model has the connectors and the header. You mentioned you didn't want the header, but I found this model with it and it matches nicely with the female header on the board.
front_prototype

### CODE REVIEW

**Comment by CRImier** [comment]
The problem with the header is as follows - the Pi Zero is actually soldered to the male pin header of the back board, and not even in the way that's shown on the picture - the connector is soldered as it should be, and then the Pi Zero is soldered on top of it. It's the only more-or-less good way to connect them all together that I found, and the 3D model should reflect that - both so that we can render assembly instructions from it, and so that the phone thickness is right (needed for 3D modelling, though lack of setting to tweak PCB thickness in KiCad is bad in this regard).

**Comment by CRImier** [comment]
So, it does need a model without the header, or sources for this model,

**Comment by dwaq** [comment]
I think I understand what you're saying, but can you provide some photos? Also, I guess I need to move the Pi to the back board?

**Comment by CRImier** [comment]
Yup, I think it would be logical to place the Pi on the back board. Pi on the back board header - unsoldered
It's not soldered on this picture, but I hope the concept is clear.

**Comment by dwaq** [comment]
Yeah, that's what I was thinking. I'll get on the modifications. Probably will come in a new PR.

**Comment by dwaq** [comment]
Fix applied in #36

**Pull request closed without merging**
