### PR TITLE
replace 3D model of R3-R10

### PR DESCRIPTION
**Pull request by dwaq**
R3-R10 used to have a 3D model of 0805_handsoldering, which did not
actually have a 3D model in KiCad. I replaced the model with the "plain"
0805 resistor model, which does show up in the 3D viewer.

Am I wasting my time here? There's a file for the 3D model of r_0805_handsoldering but is not displaying on my system. Should I continue down the list of parts that use this model or am I just changing things with no real benefit?

In reference to #12

### CODE REVIEW

**Comment by CRImier** [comment]
Hi! Thank you for your help, first and foremost!

Components not being displayed is weird, what's the KiCad version you're using? Here is how it looks in my 3D viewer: 

All resistors are present

I opened the board files in Notepad++ and just replaced them with Search+Replace, KiCad has very text-editor-friendly files, check out b58b3d8fa diff and check if it works for you =) It's very weird, though, how the .kicad_pcb files mention more 3D models, but don't show them. 

Also, while it's good to see smaller components in 3D (easier to find place for new features on the board), the smaller components are not that important for case building, it's usually components that need holes in the case (buttons, expansion 2.54 headers, audio jack, USB port, microphone etc.) and larger components (like ESP8266, it's good to know it's there to avoid placing other components that'd interfere). I'll start adding information about those in the #12 issue description =)

**Comment by dwaq** [comment]
I just wanted to start with something small before I moved onto custom components.

Prior to your b58b3d8 commit, this is what the board looked like on my system:
old
After that commit, it looked like this:
new
You can see the difference in R7, etc in the bottom left.
Another detail is how D1 actually deleted in the new commit. I noticed that the MiniMELF didn't fit on the pads on the front_pcb, but it looks like it fits now. Maybe there is an issue with my system.
Is your image before or after the latest commit?
I'm using KiCad 4.0.6 on Win7, which appears to be the latest version.
A detailed list of important components would be very helpful.

**Comment by CRImier** [comment]
Hi! Starting with small components - sure! Try this, the project license seems to be compatible: [ESP-12 3D model repo](https://github.com/jdunmire/kicad-ESP8266)

**Comment by CRImier** [comment]
My image is before the commit I did. Here's a new image: new image, looks the same, I think

I'm using KiCad 4.0.4 on Windows 8.1, I'll update the version now so that we have consistent results.

Then it might be that D1 needs the MiniMELF_HandSoldering.wrl in the new version, instead of MiniMELF.wrl.

List of components? Sure, [added here](https://github.com/ZeroPhone/ZeroPhone-PCBs/issues/12#issuecomment-302165176)

**Comment by CRImier** [comment]
Hi! I installed KiCad 4.0.6, now the 3D render seems to be like yours =)

**Comment by CRImier** [comment]
Closing, the issue was fixed and is no longer relevant.

**Pull request closed without merging**
