### PR TITLE
Keypad 3d buttons

### PR DESCRIPTION
**Pull request by dwaq**
* Added the 4-pin switches for UP1, DOWN1, LEFT1, RIGHT1, OK1, N0-N9, N*1, N#1
* Added the 2-pin switches for C1-C6, GREEN1, RED1

They're all uncolored (as seen below), but it is probably possible to color them if it does matter.
I've also added the appropriate attributions. 
keypad_prototype

### CODE REVIEW

**Comment by CRImier** [comment]
Looks awesome, accepted!

**Comment by dwaq** [comment]
After noticing the number keys in [this photo](https://github.com/ZeroPhone/ZeroPhone-PCBs/issues/12#issuecomment-302565912), the number keys don't have the same height as they do on your physical board. It might be possible to go in and change it, but we'd need to determine what needs changed and what is correct.
front_prototype

**Comment by CRImier** [comment]
Hi! Yes, I was thinking about that. We'd need the 3D model changed, I can measure the distance between the top of the key and the top of the base and get back to you in 3-4 hours.

**Comment by CRImier** [comment]
Hi! Sorry for the delay. Measured distance between top of the key and top of the key base - it's 1.1mm (so, basically, the round metal part is sticking out by 1.1mm).

**Pull request merged**
