### PR TITLE
generate side button

### PR DESCRIPTION
**Pull request by dwaq**
See #28 

Check my dimensions in the .scad file. Are they correct? The datasheet and your measurements and the PCB silkscreen disagree with each other.

I can color the base silver and the pin black once the dimensions are finalized.

Also, should I add 4 terminals?

Does this alignment look correct? Should I move the button closer to the edge of the board?
keypad_prototype

### CODE REVIEW

**Comment by CRImier** [comment]
Hi! The most important part was - the distance between the board edge and the pin edge is 0.4mm, and it's centered compared to the pads. The silkscreen can be wrong, indeed, I haven't checked it and wouldn't just blindly follow it =) As the datasheet lists many different buttons and I don't know which of them is the model I'm using - don't mind it too much, it might just have had some misc data that could have been useful, that's why I linked it.

**Comment by dwaq** [comment]
The one pad that I looked at needed to be moved 0.043mm to stick out exactly 4mm. It's so small that I'm going to ignore it and just place the parts at 0,0,0.

**Comment by dwaq** [comment]
How it looks now:
front_prototype
I think this one is ready to merge and close.

**Comment by CRImier** [comment]
Yeah, if the difference is so small, no problems. Merged, thank you very much!

**Pull request merged**
