### PR TITLE
Display

### PR DESCRIPTION
**Pull request by dwaq**
Used dimensions from #24 , EXCEPT changed "Total screen height" to 32mm because panel height + pcb top + pcb bottom (23+5+4) = 32mm.

Model is uncolored. Probably want PCB blue, display edges black? I think you can also add a photo to the display face, so it would be cool to add the ZeroPhone logo.

The position at X and Y are approximate. I was lazy and didn't want to calculate where exactly to put it.
Z position places the display flush with the header.
Rotation required due to model and PCB differences.

front_prototype

### CODE REVIEW

**Comment by CRImier** [comment]
32mm is totally OK, I think that could very well be the actual dimension of it, and tolerances seem to allow for it.

I will check and calculate the coordinates - the display should be centered to the 6-pin header, but I just understood I didn't give the PCB-top-to-header-center distance, so I'll check it myself =) Flush with the header is exactly how it works now. 

Yes, blue PCB and black display would be awesome. As for the photo - would be cool to put it in active area, so that it can be used as sort of a guide for the display cutout, I'll try and figure out the offset and photo dimensions and post them here. BTW, I'm curious, would the photo have to be linked to .wrl or to the model?

**Comment by dwaq** [comment]
You may not need to physically measure the location of the header. I think what is missing is the relationship of P1 (where I'm placing the 3D model) to P2 (the header). I'm sure it's possible to find this relationship from the pcb model, but I haven't done that yet.

I believe you can link it to the wrl. [good source?](http://cs.iupui.edu/~aharris/mm/texture/texture.html) I tried a few tools to get that working this morning to no avail. A friend told me that it should be possible in Autodesk Fusion, so I'll have to try it when I have access to a computer with that program installed.

**Comment by dwaq** [comment]
I was able to hack an image into the .wrl. I can see it works in MeshLab (first screenshot), but it's transparent in KiCad (2nd image). I'll have to dig in deeper to see why it's not working.
snapshot00
front_prototype

I also need to color the PCB and screen edges, but I know how to do that and can add those in after I get this photo working. Once it's working, you can replace the image and it should update the model since they're linked together.

**Comment by dwaq** [comment]
OK, [KiCad doesn't support textures](https://forum.kicad.info/t/does-the-3d-viewer-support-textures/1577). I think I can make it so it's a solid color and also has the texture available for programs that support it.

**Comment by dwaq** [comment]
It was still broken when I applied the color and the texture simultaneously so it's now color only.
I used silver around the edges because it was difficult to tell there was depth on the display when it was all black.
front_prototype


If my assumptions made in a1a1244 are correct (also copied below), then this branch is ready to be merged.

This assumes that the P1 header is centered vertically in the 5mm gap above the display on the pisplay PCB
This also assumes that the P2 header is centered horizontally on the PCB

**Comment by CRImier** [comment]
@dwaq Could you add some "display active area" marker? Like, a smaller block in a different color on top of the panel (and probably make the "panel" block less thick so that the total thicknessis still valid). This is necessary so that cases can be made knowing which area is active, so as to avoid showing the black panel outline (and controller area) which is never going to show an image.
TaoBao listing image
This image isn't for the exact same breakouts that I'm using, but it seems to show the active area position, more or less

**Comment by CRImier** [comment]
Thank you for the work, BTW!

**Comment by dwaq** [comment]
Yeah, I can add that. Can you send me the dimensions of the keep out area on the left/right and top/bottom of the display?

**Comment by CRImier** [comment]
You mean, keepout from the panel borders to the active area? It's on the photo I linked a two comments earlier =) The photo shows the same panel - just a different breakout.

**Pull request merged**
